name: CI

on:
    pull_request:
    push:
        branches: [ master ]

# this fixes the input device is not a TTY .. see https://github.com/docker/compose/issues/5696
env:
    MYSQL_HOST: '127.0.0.1'
    SHELL_VERBOSITY: 1

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                dependencies: ['highest']
            fail-fast: false
        env:
            PHP_CS_FIXER_FUTURE_MODE: '1'
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: intl, bcmath, curl, openssl, mbstring
                    ini-values: memory_limit=-1
                    tools: composer, php-cs-fixer
                    coverage: none

            -   name: Run PHP-CS-Fixer fix
                run: php-cs-fixer fix --dry-run --diff --ansi

    phpunit:
        name: PHPUnit PHP ${{ matrix.php }} ${{ matrix.dependency }} (Symfony ${{ matrix.symfony }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - '8.1'
                    - '8.2'
                dependency:
                    - ''
                symfony:
                    - '5.4.*'
                    - '6.3.*'
                    - '6.4.*'
                    - '7.0.*'
                include:
                    - php: '8.1'
                      symfony: '5.4.*'
                      dependency: 'lowest'
                exclude:
                    - php: '8.1'
                      symfony: '7.0.*'
            fail-fast: false

        services:
            # To keep in sync with fixtures/Functional/config/doctrine.yml and docker-compose.yaml
            mysql:
                image: mysql:8.0
                ports:
                    - 3307:3306
                env:
                    MYSQL_DATABASE: hautelook_alice_bundle
                    MYSQL_ROOT_USER: root
                    MYSQL_ROOT_PASSWORD: password
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer, flex
                    extensions: intl, bcmath, curl, openssl, mbstring
                    ini-values: memory_limit=-1

            -   name: Update project dependencies
                if: matrix.dependency == ''
                run: composer update --no-progress --ansi --prefer-stable
                env:
                    SYMFONY_REQUIRE: ${{ matrix.symfony }}

            -   name: Update project dependencies lowest
                if: matrix.dependency == 'lowest'
                run: composer update --no-progress --ansi --prefer-stable --prefer-lowest
                env:
                    SYMFONY_REQUIRE: ${{ matrix.symfony }}

            -   name: Wait for MySQL
                run: |
                    while ! mysqladmin ping --host=$MYSQL_HOST --user=root --password=$MYSQL_ROOT_PASSWORD --port=3307; do
                        sleep 1
                    done

            -   name: Run tests
                run: vendor/bin/phpunit --verbose --stop-on-failure
